import '../ai_image_search_screen/widgets/frame1_item_widget.dart';import '../ai_image_search_screen/widgets/frame2_item_widget.dart';import 'package:flutter/material.dart';import 'package:genteel/core/app_export.dart';import 'package:genteel/widgets/app_bar/appbar_leading_image.dart';import 'package:genteel/widgets/app_bar/appbar_title.dart';import 'package:genteel/widgets/app_bar/appbar_trailing_circleimage.dart';import 'package:genteel/widgets/app_bar/custom_app_bar.dart';import 'package:genteel/widgets/custom_elevated_button.dart';import 'package:genteel/widgets/custom_icon_button.dart';import 'package:genteel/widgets/custom_outlined_button.dart';class AiImageSearchScreen extends StatelessWidget {const AiImageSearchScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: SizedBox(width: SizeUtils.width, child: SingleChildScrollView(child: Container(margin: EdgeInsets.only(bottom: 5.v), padding: EdgeInsets.symmetric(horizontal: 20.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("Upload the image you want AI to search!", style: CustomTextStyles.bodyMediumBluegray90001), SizedBox(height: 12.v), _buildComponentSeven(context), SizedBox(height: 28.v), CustomImageView(imagePath: ImageConstant.imgRectangle3779, height: 169.v, width: 335.h, radius: BorderRadius.vertical(top: Radius.circular(4.h))), _buildOne(context), Divider(color: appTheme.pink300), SizedBox(height: 25.v), Text("Similar Bag Style", style: CustomTextStyles.titleMediumBluegray90001), SizedBox(height: 7.v), _buildFrame1(context), SizedBox(height: 21.v), Text("Stores Nearby Having Similar Style", style: CustomTextStyles.titleMediumBluegray90001), SizedBox(height: 7.v), _buildFrame2(context), SizedBox(height: 24.v), CustomOutlinedButton(height: 52.v, text: "Was this helpful?", buttonStyle: CustomButtonStyles.outlineGray, buttonTextStyle: CustomTextStyles.titleMediumNunitoBlack900), SizedBox(height: 10.v), CustomOutlinedButton(height: 52.v, text: "Generate more", buttonStyle: CustomButtonStyles.outlinePrimary, buttonTextStyle: CustomTextStyles.titleMediumNunitoBlack900)])))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 37.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 20.h, top: 15.v, bottom: 16.v), onTap: () {onTapArrowLeft(context);}), title: AppbarTitle(text: "Genteel AI", margin: EdgeInsets.only(left: 10.h)), actions: [AppbarTrailingCircleimage(imagePath: ImageConstant.imgEllipse16, margin: EdgeInsets.fromLTRB(20.h, 7.v, 20.h, 8.v))]); } 
/// Section Widget
Widget _buildComponentSeven(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Container(width: 195.h, decoration: AppDecoration.fillOnPrimaryContainer.copyWith(borderRadius: BorderRadiusStyle.circleBorder20), child: Row(mainAxisAlignment: MainAxisAlignment.spaceEvenly, children: [Padding(padding: EdgeInsets.only(top: 10.v, bottom: 11.v), child: Text("Chat", style: CustomTextStyles.titleMediumNunitoBluegray400SemiBold)), CustomElevatedButton(height: 44.v, width: 69.h, text: "Image", buttonStyle: CustomButtonStyles.fillGreenA, buttonTextStyle: CustomTextStyles.titleMediumNunitoOnPrimaryContainer_1), Padding(padding: EdgeInsets.only(top: 10.v, bottom: 11.v), child: Text("Video", style: CustomTextStyles.titleMediumNunitoBluegray400))])), CustomImageView(imagePath: ImageConstant.imgSearchBlack900, height: 36.v, width: 48.h, margin: EdgeInsets.symmetric(vertical: 4.v))]); } 
/// Section Widget
Widget _buildOne(BuildContext context) { return Container(height: 29.v, width: 335.h, decoration: AppDecoration.outlineGray30001, child: Stack(alignment: Alignment.bottomRight, children: [Align(alignment: Alignment.bottomCenter, child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(left: 7.h), child: Text("Search completed.", style: CustomTextStyles.bodySmallNunitoBluegray90001)), SizedBox(height: 6.v), Divider(color: appTheme.pink300)])), Padding(padding: EdgeInsets.only(right: 9.h, bottom: 6.v), child: CustomIconButton(height: 15.adaptSize, width: 15.adaptSize, alignment: Alignment.bottomRight, child: CustomImageView()))])); } 
/// Section Widget
Widget _buildFrame1(BuildContext context) { return SizedBox(height: 77.v, child: ListView.separated(scrollDirection: Axis.horizontal, separatorBuilder: (context, index) {return SizedBox(width: 6.h);}, itemCount: 4, itemBuilder: (context, index) {return Frame1ItemWidget();})); } 
/// Section Widget
Widget _buildFrame2(BuildContext context) { return SizedBox(height: 77.v, child: ListView.separated(scrollDirection: Axis.horizontal, separatorBuilder: (context, index) {return SizedBox(width: 6.h);}, itemCount: 4, itemBuilder: (context, index) {return Frame2ItemWidget();})); } 

/// Navigates back to the previous screen.
onTapArrowLeft(BuildContext context) { Navigator.pop(context); } 
 }
