import 'package:flutter/material.dart';import 'package:genteel/core/app_export.dart';import 'package:genteel/widgets/app_bar/appbar_leading_image.dart';import 'package:genteel/widgets/app_bar/appbar_subtitle.dart';import 'package:genteel/widgets/app_bar/custom_app_bar.dart';import 'package:genteel/widgets/custom_elevated_button.dart';class CheckoutOneScreen extends StatelessWidget {const CheckoutOneScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 12.h, vertical: 19.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.symmetric(horizontal: 8.h), child: _buildTotal(context, orderText: "Shipping address", priceText: "Edit")), SizedBox(height: 14.v), Padding(padding: EdgeInsets.only(left: 8.h), child: Text("Daph Edwards", style: CustomTextStyles.titleMediumNunitoBluegray90001)), SizedBox(height: 8.v), Container(width: 224.h, margin: EdgeInsets.only(left: 8.h), child: Text("4517 Washington Ave. Manchester, Kentucky 39495", maxLines: 2, overflow: TextOverflow.ellipsis, style: CustomTextStyles.bodyMediumGray700.copyWith(height: 1.57))), SizedBox(height: 10.v), Padding(padding: EdgeInsets.only(left: 8.h), child: Text("(405) 555-0128", style: CustomTextStyles.bodyLargeNunitoGray700)), SizedBox(height: 27.v), Divider(indent: 8.h), SizedBox(height: 19.v), _buildCreditCard(context), SizedBox(height: 20.v), Divider(indent: 8.h), SizedBox(height: 21.v), Padding(padding: EdgeInsets.symmetric(horizontal: 8.h), child: _buildTotal(context, orderText: "Order:", priceText: "370")), SizedBox(height: 11.v), Padding(padding: EdgeInsets.symmetric(horizontal: 8.h), child: _buildTotal(context, orderText: "Discount", priceText: "10.99")), SizedBox(height: 10.v), Padding(padding: EdgeInsets.symmetric(horizontal: 8.h), child: _buildTotal(context, orderText: "Delivery Fees ", priceText: "Free")), Spacer(), SizedBox(height: 5.v), Padding(padding: EdgeInsets.symmetric(horizontal: 8.h), child: _buildTotal(context, orderText: "Total:", priceText: "359"))])), bottomNavigationBar: _buildPayNow(context))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 44.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 20.h, top: 16.v, bottom: 15.v), onTap: () {onTapArrowLeft(context);}), centerTitle: true, title: AppbarSubtitle(text: "Checkout")); } 
/// Section Widget
Widget _buildCreditCard(BuildContext context) { return Padding(padding: EdgeInsets.symmetric(horizontal: 8.h), child: Row(children: [CustomImageView(imagePath: ImageConstant.imgCloseRedA700, height: 32.v, width: 52.h), Padding(padding: EdgeInsets.only(left: 11.h, top: 5.v, bottom: 4.v), child: Text("Credit Card ending  ••••24", style: CustomTextStyles.bodyLargeNunitoBluegray90001_1)), Spacer(), CustomImageView(imagePath: ImageConstant.imgArrowRightBlueGray9000120x20, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.symmetric(vertical: 6.v))])); } 
/// Section Widget
Widget _buildPayNow(BuildContext context) { return CustomElevatedButton(text: "Pay now", margin: EdgeInsets.only(left: 20.h, right: 20.h, bottom: 68.v)); } 
/// Common widget
Widget _buildTotal(BuildContext context, {required String orderText, required String priceText, }) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text(orderText, style: CustomTextStyles.titleLarge_1.copyWith(color: appTheme.black900)), Text(priceText, style: CustomTextStyles.titleLarge_1.copyWith(color: appTheme.black900))]); } 

/// Navigates back to the previous screen.
onTapArrowLeft(BuildContext context) { Navigator.pop(context); } 
 }
