import 'package:flutter/material.dart';import 'package:genteel/core/app_export.dart';import 'package:genteel/widgets/app_bar/appbar_leading_image.dart';import 'package:genteel/widgets/app_bar/appbar_subtitle.dart';import 'package:genteel/widgets/app_bar/custom_app_bar.dart';import 'package:genteel/widgets/custom_elevated_button.dart';class CheckoutScreen extends StatelessWidget {const CheckoutScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 20.h, vertical: 14.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("Shipping Method".toUpperCase(), style: CustomTextStyles.bodyMediumLoraBluegray400), SizedBox(height: 8.v), _buildFrameFortyTwo(context), SizedBox(height: 31.v), Text("Shipping address".toUpperCase(), style: CustomTextStyles.bodyMediumLoraBluegray400), SizedBox(height: 8.v), _buildText(context, paymentMethodText: "Add shipping address", arrowRightImage: ImageConstant.imgPlus), SizedBox(height: 31.v), Text("Payment method".toUpperCase(), style: CustomTextStyles.bodyMediumLoraBluegray400), SizedBox(height: 8.v), _buildText(context, paymentMethodText: "Select payment method", arrowRightImage: ImageConstant.imgArrowRightBlueGray90001), SizedBox(height: 5.v)])), bottomNavigationBar: _buildPay359(context))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 44.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 20.h, top: 16.v, bottom: 15.v), onTap: () {onTapArrowLeft(context);}), centerTitle: true, title: AppbarSubtitle(text: "Checkout")); } 
/// Section Widget
Widget _buildFrameFortyTwo(BuildContext context) { return Container(padding: EdgeInsets.symmetric(horizontal: 17.h, vertical: 12.v), decoration: AppDecoration.fillGray.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Padding(padding: EdgeInsets.only(left: 3.h, top: 1.v), child: Text("Shipping method", style: CustomTextStyles.bodyLargeNunitoBluegray90001_1)), Spacer(), Padding(padding: EdgeInsets.only(top: 1.v), child: Text("Free".toUpperCase(), style: CustomTextStyles.bodyMediumBluegray90001)), CustomImageView(imagePath: ImageConstant.imgArrowDownBlueGray900011, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.only(left: 8.h, top: 1.v))])); } 
/// Section Widget
Widget _buildPay359(BuildContext context) { return CustomElevatedButton(text: "Pay - 359 ", margin: EdgeInsets.only(left: 20.h, right: 20.h, bottom: 68.v)); } 
/// Common widget
Widget _buildText(BuildContext context, {required String paymentMethodText, required String arrowRightImage, }) { return Container(padding: EdgeInsets.symmetric(horizontal: 20.h, vertical: 12.v), decoration: AppDecoration.fillGray.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(top: 1.v), child: Text(paymentMethodText, style: CustomTextStyles.bodyLargeNunitoBluegray90001_1.copyWith(color: appTheme.blueGray90001))), CustomImageView(imagePath: arrowRightImage, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.only(top: 1.v))])); } 

/// Navigates back to the previous screen.
onTapArrowLeft(BuildContext context) { Navigator.pop(context); } 
 }
